name: Court Street
favicon: null
layout_spectrum: 0.14258367265574634
typography_spectrum: 0.7794980162288994
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3383827470242977
  lightness: 0.1861348282545805
  saturation: 0.9576646874193102
  rhythmicContrast: 0.6043964065611362
purpose: []
